project_id = "otwcyimspsqxmbwzlmjo"

[functions.generate-training-plan]
verify_jwt = true

[functions.parse-training-plan]
verify_jwt = true

[functions.generate-day-details]
verify_jwt = true

[functions.strava-auth]
verify_jwt = true

[functions.strava-callback]
verify_jwt = false

[functions.fetch-strava-data]
verify_jwt = true